version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_NAME}'
    ports:
      - '${DB_PORT}:5433'
    volumes:
      - db_data:/var/lib/docker/volumes/postgresql_volume/_data

volumes:
    db_data: